name: Docker Image CI

on:
  workflow_dispatch:
  schedule:
    - cron: '30 17 * * *'
  push:
    branches:
      - Development

jobs:

  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3

    - name: Login To Registry
      uses: docker/login-action@v2
      with:
        registry: "${{ vars.DOCKER_REGISTRY_URL }}"
        username: "${{ secrets.DOCKER_REGISTRY_USER }}"
        password: "${{ secrets.DOCKER_REGISTRY_PASSWORD }}"

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build Steamcmd Image
      uses: docker/build-push-action@v3
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: "${{ vars.DOCKER_REGISTRY_URL }}/steamcmd:latest"
        cache-from: type=registry,ref=${{ vars.DOCKER_REGISTRY_URL }}/steamcmd:latest
        cache-to: type=inline
